apiVersion: v1
kind: PersistentVolumeClaim
metadata:
<<<<<<< HEAD
=======
  name: mysql-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
>>>>>>> 288ed07856be2ef0e141ca0ae1c4324aea376035
  name: laravel-storage-pvc
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
